version: "3.9"

volumes:
  postgres_data_websocket:

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: websocket_frontend
    tty: true
    volumes:
      - .:/app
      # - node_modules:/app/frontend/node_modules
    ports:
      - 5174:5173
    command: yarn dev

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: websocket_backend
    ports:
      - 8081:8080
    tty: true
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./redis/redis.conf:/etc/redis.conf
